# Generated by Django 5.0.2 on 2024-03-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_category_posts_post_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='category',
        ),
    ]
